openapi: 3.0.0
info:
  version: 0.0.4-rc
  title: vitessce-api
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: >
    This API
      - includes JSON schemas [Vitessce](https://github.com/hms-dbmi/vitessce) could use internally,
      - and is an API Vitessce could use in the future,
      - and hopefully is the start of an API for web tools across HuBMAP.
